### ISSUE TITLE
Missing file extension for "meteor/meteor"

### ISSUE THREAD

**Issue by smeijer** [clayne11/eslint-import-resolver-meteor#17]
When using this resolver, I get some errors on missing file extensions.

**eslint config**

``` yml
extends: "airbnb"

parser: "babel-eslint"
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: "module"

rules:
  # otherwise eslint will throw errors about meteor/* being missing
  import/no-extraneous-dependencies: "off"

  # _id and private vars are prefixed with _
  no-underscore-dangle: "off"

settings:
  import/resolver: "meteor"

```

**eslint error:**

```
1:26  error  Missing file extension for "meteor/accounts-base"         import/extensions
2:24  error  Missing file extension for "meteor/meteor"                import/extensions
```

**code file:**

``` js
import { Accounts } from 'meteor/accounts-base';
import { Meteor } from 'meteor/meteor';
```

**Comment by damonmaria** [comment]
This has only started happening for me with updating AirBnb config and ESLint.

**Comment by nelsyeung** [comment]
https://github.com/airbnb/javascript/commit/f6dab799b8fa1346f1cc3fdfdbe9c9fbeef7baf6 introduced:

``` js
'import/extensions': ['error', 'always', {
  js: 'never',
  jsx: 'never',
}],
```

Previously was:

``` js
'import/extensions': ['off', 'never'],
```

I don't like this fix but you just have to turn it off like Airbnb previously:

``` yml
rules:
  import/extensions:
    - off
    - never
```
